sumo: fix build dm520, dm820 and dm7080
ERROR: Nothing RPROVIDES 'kernel-3.4-4.0-dm820' (but /home/hains/openpli-oe-core/pli-extras/meta-dream/recipes-bsp/drivers/
dreambox-dvb-modules-dm7080_3.4-4.0-20181002.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'kernel-4.0-.1-dm7080' is unbuildable, removing...